### ISSUE TITLE
The Chart stored in the chart museum for v3.2.16 has the wrong image tag

### ISSUE THREAD

**Issue by merello-notified** [phntom/charts#1]
The chart stored in the chart museum for v3.2.16 has these values:

```yaml
image:
  repository: "phntom/oauth2-proxy"
  tag: "v7.4.0@sha256:8ded407782644dd442afa5e986fb602c363d8a36d0a337208eda8e71248a9ce7"
  pullPolicy: "IfNotPresent"
```

that SHA256 is wrong. The versioned [values.yaml](https://github.com/phntom/charts/blob/master/oauth2-proxy/values.yaml#L33) on this repository is already correct:
```yaml
image:
  repository: "phntom/oauth2-proxy"
  tag: "v7.4.0@sha256:cd0ac2b1b5ac4574a6c575ee655740cf9a70c37d1787087f3c9ea295e6697bce"
  pullPolicy: "IfNotPresent"
```

The chart needs to be updated on the chart museum to use the correct SHA256, otherwise the deployment of 3.2.16 cannot pull the image.

Could you address that?
Thanks!
